name: PR Test with Docker Compose + Poetry

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
          # Wait for services to be fully ready
          sleep 10
          docker-compose exec load-tester poetry run pytest

      - name: Shut down Docker Compose
        if: always()
        run: docker-compose down
