# .github/workflows/resolve-rchash-conflicts.yml
name: Resolve RCHASH Conflicts After Merge

on:
  push:
    branches:
      - main
    paths:
      - 'helm-chart/Chart.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  resolve-conflicts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Resolve RCHASH conflicts in open PRs
      run: |
        # Get all open PRs using GitHub CLI
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        
        # Get open PRs as JSON
        OPEN_PRS=$(gh pr list --state open --base main --json number,headRefName,title)
        
        echo "Open PRs: $OPEN_PRS"
        
        # Process each PR
        echo "$OPEN_PRS" | jq -c '.[]' | while read pr; do
          PR_NUMBER=$(echo "$pr" | jq -r '.number')
          PR_BRANCH=$(echo "$pr" | jq -r '.headRefName')
          PR_TITLE=$(echo "$pr" | jq -r '.title')
          
          echo ""
          echo "--- Processing PR #$PR_NUMBER: $PR_TITLE ---"
          echo "Branch: $PR_BRANCH"
          
          # Check if Chart.yml exists in PR branch
          if ! git show origin/$PR_BRANCH:helm-chart/Chart.yml > /dev/null 2>&1; then
            echo "PR #$PR_NUMBER: No Chart.yml found, skipping"
            continue
          fi
          
          # Get RCHASH from PR branch (before any conflicts)
          PR_RCHASH=$(git show origin/$PR_BRANCH:helm-chart/Chart.yml | grep "RCHASH:" | awk '{print $2}' | tr -d ' ')
          
          # Get RCHASH from main branch
          MAIN_RCHASH=$(git show main:helm-chart/Chart.yml | grep "RCHASH:" | awk '{print $2}' | tr -d ' ')
          
          echo "PR #$PR_NUMBER RCHASH: $PR_RCHASH"
          echo "Main RCHASH: $MAIN_RCHASH"
          
          if [ "$PR_RCHASH" = "$MAIN_RCHASH" ]; then
            echo "PR #$PR_NUMBER: No RCHASH conflict, skipping"
            continue
          fi
          
          # Checkout PR branch
          git checkout -B temp-$PR_BRANCH origin/$PR_BRANCH
          
          # Check if there would be conflicts by doing a test merge
          if git merge main --no-commit --no-ff > /dev/null 2>&1; then
            echo "PR #$PR_NUMBER: No conflicts at all, cleaning up"
            git merge --abort
            continue
          fi
          
          echo "PR #$PR_NUMBER: Conflicts detected, checking if Chart.yml is the only conflict..."
          
          # Start merge to see what files have conflicts
          git merge main --no-commit --no-ff || true
          
          # Get list of files with conflicts
          CONFLICT_FILES=$(git diff --name-only --diff-filter=U)
          echo "Files with conflicts: $CONFLICT_FILES"
          
          # Check if Chart.yml is the ONLY file with conflicts
          if [ "$CONFLICT_FILES" = "helm-chart/Chart.yml" ]; then
            echo "PR #$PR_NUMBER: Only Chart.yml has conflicts, proceeding with resolution..."
            
            # Resolve Chart.yml conflict by keeping main's version but with PR's RCHASH
            git show main:helm-chart/Chart.yml > helm-chart/Chart.yml.tmp
            sed -i "s/RCHASH: .*/RCHASH: $PR_RCHASH/" helm-chart/Chart.yml.tmp
            mv helm-chart/Chart.yml.tmp helm-chart/Chart.yml
            
            # Mark as resolved
            git add helm-chart/Chart.yml
            
            # Complete the merge
            git commit -m "chore: merge main and resolve RCHASH conflict, keep PR value $PR_RCHASH"
            
            # Push to PR branch
            git push origin temp-$PR_BRANCH:$PR_BRANCH
            
            echo "PR #$PR_NUMBER: Successfully resolved RCHASH conflict and pushed"
            
            # Comment on PR about successful resolution
            gh pr comment $PR_NUMBER --body "🔧 **RCHASH Conflict Auto-Resolved**
        
        A merge to main caused a conflict in \`helm-chart/Chart.yml\`. The conflict has been automatically resolved by:
        
        - ✅ **Merging latest changes from main**
        - ✅ **Keeping your PR's RCHASH**: \`$PR_RCHASH\`
        
        Your PR is now up-to-date and ready for review! 🚀"
            
          else
            echo "PR #$PR_NUMBER: Multiple files have conflicts, cannot auto-resolve"
            
            # Abort the merge since we can't auto-resolve
            git merge --abort
            
            # Check if Chart.yml is among the conflicted files
            if echo "$CONFLICT_FILES" | grep -q "helm-chart/Chart.yml"; then
              CHART_CONFLICT_MSG="⚠️ **Chart.yml** (including RCHASH conflict)"
            else
              CHART_CONFLICT_MSG=""
            fi
            
            # Create a list of conflicted files for the comment
            CONFLICT_LIST=$(echo "$CONFLICT_FILES" | sed 's/^/- `/' | sed 's/$/`/')
            
            # Comment on PR about conflicts that need manual resolution
            gh pr comment $PR_NUMBER --body "⚠️ **Manual Conflict Resolution Required**
        
        A merge to main has created conflicts in multiple files that require your attention:
        
        $CONFLICT_LIST
        
        $CHART_CONFLICT_MSG
        
        **Next Steps:**
        1. Pull the latest changes from main into your branch
        2. Resolve the conflicts manually
        3. For Chart.yml conflicts, please keep your RCHASH value: \`$PR_RCHASH\`
        
        The automated resolution was skipped because multiple files have conflicts that require developer review."
          fi
          
          # Clean up
          git checkout main
          git branch -D temp-$PR_BRANCH || true
          
        done
        
        echo ""
        echo "--- Conflict resolution completed ---"