name: Update RCHASH on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-rchash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # This checks out the source branch of the PR

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate new RCHASH value
        id: generate_hash
        run: |
          import hashlib
          import time
          raw = f"{time.time()}".encode("utf-8")
          print(f"::set-output name=hash::{hashlib.sha256(raw).hexdigest()[:8]}")
        shell: python

      - name: Update Chart.yaml with new RCHASH
        run: |
          sed -i "s/^  RCHASH: .*/  RCHASH: ${{ steps.generate_hash.outputs.hash }}/" helm-chart/Chart.yml

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push if changes exist
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add helm-chart/Chart.yml
          if ! git diff --cached --quiet; then
            git commit -m "Update RCHASH on PR"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}
          fi
