# .github/workflows/update-rchash.yml
name: Update RCHASH in Helm Chart

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main  # Adjust this to your default branch name

permissions:
  contents: write
  pull-requests: write

jobs:
  update-rchash:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Generate new RCHASH
      id: generate-hash
      run: |
        # Generate a hash based on PR number and current timestamp
        PR_NUMBER="${{ github.event.number }}"
        TIMESTAMP=$(date +%s)
        NEW_HASH=$(echo "${PR_NUMBER}-${TIMESTAMP}" | sha256sum | cut -c1-6)
        echo "new_hash=${NEW_HASH}rc" >> $GITHUB_OUTPUT
        echo "Generated RCHASH: ${NEW_HASH}rc"

    - name: Update RCHASH in Chart.yml
      run: |
        # Update the RCHASH value in the Chart.yml file
        sed -i "s/RCHASH: .*/RCHASH: ${{ steps.generate-hash.outputs.new_hash }}/" helm-chart/Chart.yml
        
        # Verify the change
        echo "Updated Chart.yml content:"
        cat helm-chart/Chart.yml | grep RCHASH

    - name: Check if changes were made
      id: check-changes
      run: |
        if git diff --quiet helm-chart/Chart.yml; then
          echo "No changes detected"
          echo "changes_made=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "changes_made=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.changes_made == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add helm-chart/Chart.yml
        git commit -m "chore: update RCHASH to ${{ steps.generate-hash.outputs.new_hash }} for PR #${{ github.event.number }}"
        git push origin HEAD:${{ github.head_ref }}

    - name: Comment on PR
      if: steps.check-changes.outputs.changes_made == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🔄 **RCHASH Updated**\n\nThe RCHASH value has been automatically updated to: \`${{ steps.generate-hash.outputs.new_hash }}\``
          });